// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace YapistirVeDegistir
{
    internal sealed partial class Vsix
    {
        public const string Id = "YapistirVeDegistir.46a0a691-4e8f-4ed8-9a74-90a9eebd3bbc";
        public const string Name = "YapistirVeDegistir";
        public const string Description = @"Paste and replace extension is simple way to surround selected text with copied text before. Copy a text which is contain a * character. Next select another text and press CTRL+ALT+V double time. Your selected text will insert into copied text via replaced with * character.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Serhat Mercan";
        public const string Tags = "paste and replace, paste, simple replace";
    }
}
